name: CI CD - Bot Whatsapp Telegram

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run typecheck || true

  # cd:
  #   runs-on: self-hosted
  #   needs: ci

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Deploy via SSH
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           cd ~/www/hono-bot-wa

  #           sudo docker compose down || true

  #           git pull origin main

  #           sudo mkdir -p /opt/wa-auth
  #           sudo mkdir -p /opt/wa-cache

  #           sudo find /opt/wa-auth -name "Singleton*" -delete || true
  #           sudo find /opt/wa-auth -name "LOCK" -delete || true
  #           sudo rm -rf /tmp/puppeteer* || true

  #           sudo pkill chromium || true
  #           sudo pkill chrome || true

  #           sudo docker compose up -d --build
  #           sudo docker image prune -f

      # - name: Copy env
      #   run: |
      #     if [ -f /var/www/hono-bot-wa/.env ]; then
      #       cp /var/www/hono-bot-wa/.env .env
      #     fi

      # - name: Stop old container
      #   run: docker compose down || true

      # - name: Prepare volume directories
      #   run: |
      #     sudo mkdir -p /opt/wa-auth
      #     sudo mkdir -p /opt/wa-cache

      # - name: Clean chromium lock
      #   run: |
      #     sudo find /opt/wa-auth -name "Singleton*" -type f -delete || true
      #     sudo find /opt/wa-auth -name "LOCK" -type f -delete || true
      #     sudo rm -rf /tmp/puppeteer* || true

      # - name: Kill old chromium
      #   run: |
      #     sudo pkill chromium || true
      #     sudo pkill chrome || true

      # - name: Build & Run
      #   run: sudo docker compose up -d --build

      # - name: Cleanup unused images
      #   run: sudo docker image prune -f